---
- name: Deploy OpenJDK to Windows
  hosts: windows
  vars:
    deploy_file: "java-11-openjdk-11.0.2.7-2.windows.redhat.x86_64.zip"
  tasks:
  - name: dispatch
    win_copy:
      src: /var/lib/awx/projects/projIMHK/{{ deploy_file }}
      dest: D:\tmp\
    register: file_copy
  - name: deploy zipped file
    win_unzip:
      src: D:\tmp\{{ deploy_file }}
      dest: d:\openjdk
      creates: d:\openjdk\java-11-openjdk-11.0.2.7-2.windows.redhat.x86_64
    when: file_copy is succeeded
  - name: create JAVA_HOME
    win_environment:
      level: machine
      name: JAVA_HOME
      state: present
      value: d:\openjdk\java-11-openjdk-11.0.2.7-2.windows.redhat.x86_64
    register: java_home
  - name: append java_home.value\bin to PATH
    win_path:
      scope: user
      state: present
      elements: "{{ java_home.value }}\\bin"
  - name: verify
    win_command: java.exe -version
    args: 
      chdir: "{{ java_home.value }}\\bin"
    register: java_version
  - name: print java version
    debug:
      msg: "{{ java_version.stderr_lines }}"
